<?php

/**
 * @file
 * Provides a table formatter for multifield field types.
 */

/**
 * Implements hook_field_formatter_info().
 */
function multifield_table_field_formatter_info() {
  $info = array();
  $multifields = multifield_load_all();

  if (!empty($multifields)) {
    $info['multifield_table'] = array(
      'label' => t('Table'),
      'field types' => array_keys($multifields),
      'settings' => array(
        'view_mode' => 'default',
      ),
    );
  }

  return $info;
}

/**
 * Implements hook_field_formatter_settings().
 */
function multifield_table_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  return multifield_field_formatter_settings_form($field, $instance, $view_mode, $form, $form_state);
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function multifield_table_field_formatter_settings_summary($field, $instance, $view_mode) {
  return multifield_field_formatter_settings_summary($field, $instance, $view_mode);
}

/**
 * Implements hook_field_prepare_view().
 */
function multifield_table_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items, $display = NULL) {
  return multifield_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, $items, $display);
}

/**
 * Implements hook_field_formatter_view().
 */
function multifield_table_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  if ($items) {
    $header = $rows = array();

    foreach ($items as $item) {
      // Generate the table header.
      if (!$header) {
        $instances = field_info_instances('multifield', $item['#pseudo_entity']->type);
        foreach ($instances as $name => $instance) {
          if ($instance['display'][$settings['view_mode']]['type'] != 'hidden') {
            $fields[$instance['display'][$settings['view_mode']]['weight']] = $name;
          }
        }
        ksort($fields);

        foreach ($fields as $subtype) {
          $header[$subtype] = array(
            'data' => $instances[$subtype]['label'],
            'class' => drupal_clean_css_identifier($subtype),
          );
        }
      }

      // Display field columns.
      $row = array();
      foreach ($fields as $subtype) {
        if ($cell = field_view_field('multifield', $item['#pseudo_entity'], $subtype, $settings['view_mode'], $langcode)) {
          $row[] = render($cell[0]);
        }
        else {
          $row[] = '';
        }
      }
      $rows[] = $row;
    }

    if ($rows) {
      $element[0] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#rows' => $rows,
      );
    }
  }

  return $element;
}
